### ISSUE TITLE
Missing directory and file

### ISSUE THREAD

**Issue by levilloyd** [maskedband1t/binary_akinator#2]
When running akinator.py for the first time I got these errors that appear to be from a missing directory and file:

```
python akinator.py ~/Desktop/busybox/gcc_6.5.0/busybox-1.31.1/busybox
Your CPU supports instructions that this binary was not compiled to use: AVX2
For maximum performance, you can install NMSLIB from sources
pip install --no-binary :all: nmslib
ingestion failed
Traceback (most recent call last):
  File "/Users/<removed>/Projects/binary_akinator/akinator.py", line 423, in main
    bounce_and_ingest(bounce, filename)
  File "/Users/<removed>/Projects/binary_akinator/akinator.py", line 276, in bounce_and_ingest
    if not (pickle_fs_contains(file_hash)) or bounce:
  File "/Users/<removed>/Projects/binary_akinator/akinator.py", line 310, in pickle_fs_contains
    for filename in os.listdir(pickle_directory):
FileNotFoundError: [Errno 2] No such file or directory: 'pickled_files'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/<removed>/Projects/binary_akinator/akinator.py", line 472, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/<removed>/Projects/binary_akinator/akinator.py", line 427, in main
    read_and_ingest(file_hash, filename_base)
  File "/Users/<removed>/Projects/binary_akinator/akinator.py", line 357, in read_and_ingest
    bouncer_read_df = pd.read_csv(
  File "/usr/local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/usr/local/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'buckets/ml_bucket.txt'
```

**Comment by levilloyd** [comment]
once I created the pickled_files directory and the buckets/ml_bucket.txt file (empty file), it worked.  The code should probably look for these and create them if needed.

**Comment by levilloyd** [comment]
actually it looks like it might be expecting something in the ml_bucket.txt file
```
python akinator.py ~/Desktop/busybox/gcc_6.5.0/busybox-1.31.1/busybox
Your CPU supports instructions that this binary was not compiled to use: AVX2
For maximum performance, you can install NMSLIB from sources
pip install --no-binary :all: nmslib
/bin/sh: readelf: command not found
ingestion failed
read bucket(s)
6591 elements in file
creating pickle. check pickled_files folder...
read pickle @ /Users/<removed>/Projects/binary_akinator/pickled_files/0912531912498411a34588d12e3cb445-busybox.pkl
done loading in library, created sets
entering vectorize and query
Traceback (most recent call last):
  File "/Users/<removed>/Projects/binary_akinator/akinator.py", line 472, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/<removed>/Projects/binary_akinator/akinator.py", line 455, in main
    compare_these(
  File "/Users/<removed>/Projects/binary_akinator/akinator.py", line 346, in compare_these
    vectorize_and_query(
  File "/Users/<removed>/Projects/binary_akinator/akinator.py", line 84, in vectorize_and_query
    tf_idf_matrix = vectorizer.fit_transform(_library)
  File "/usr/local/lib/python3.9/site-packages/sklearn/feature_extraction/text.py", line 2077, in fit_transform
    X = super().fit_transform(raw_documents)
  File "/usr/local/lib/python3.9/site-packages/sklearn/feature_extraction/text.py", line 1330, in fit_transform
    vocabulary, X = self._count_vocab(raw_documents, self.fixed_vocabulary_)
  File "/usr/local/lib/python3.9/site-packages/sklearn/feature_extraction/text.py", line 1220, in _count_vocab
    raise ValueError(
ValueError: empty vocabulary; perhaps the documents only contain stop words
```

**Comment by maskedband1t** [comment]
I enabled the creation of the buckets files as well as the pickled_files directory if not existing before access. Suspected the most recent issue is due to the library not having enough searchable files (not including itself) in the library at time of run. Added prompt for user to run on at least 1 more unique file for further results and directed exit. Tested this out on my own machine by deleting the library and issue no longer appeared. Made a few other associated changes as a result. Please let me know if any other issues. Changes reflected in commit c37720b

**Comment by maskedband1t** [comment]
Marking as resolved, closing
